graph LR
    AppModule-->ArticlesModule
  AppModule-->AuthModule
  AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->HttpModule
  AppModule-->MailerCoreModule
  AppModule-->MailerModule
  AppModule-->PodcastModule
  AppModule-->RedisCoreModule
  AppModule-->RedisModule
  AppModule-->SequelizeCoreModule
  AppModule-->SequelizeModule
  AppModule-->UploadModule
  AppModule-->UsersModule
  ArticlesModule-->ConfigHostModule
  ArticlesModule-->ConfigModule
  ArticlesModule-->MailerCoreModule
  ArticlesModule-->RedisCoreModule
  ArticlesModule-->SequelizeCoreModule
  AuthModule-->ConfigHostModule
  AuthModule-->ConfigModule
  AuthModule-->JwtModule
  AuthModule-->MailerCoreModule
  AuthModule-->PassportModule
  AuthModule-->RedisCoreModule
  AuthModule-->SequelizeCoreModule
  AuthModule-->UsersModule
  ConfigHostModule-->ConfigModule
  ConfigHostModule-->MailerCoreModule
  ConfigHostModule-->RedisCoreModule
  ConfigHostModule-->SequelizeCoreModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->ConfigModule
  ConfigModule-->MailerCoreModule
  ConfigModule-->RedisCoreModule
  ConfigModule-->SequelizeCoreModule
  HttpModule-->ConfigHostModule
  HttpModule-->ConfigModule
  HttpModule-->MailerCoreModule
  HttpModule-->RedisCoreModule
  HttpModule-->SequelizeCoreModule
  JwtModule-->ConfigHostModule
  JwtModule-->ConfigModule
  JwtModule-->MailerCoreModule
  JwtModule-->RedisCoreModule
  JwtModule-->SequelizeCoreModule
  MailerCoreModule-->ConfigHostModule
  MailerCoreModule-->ConfigModule
  MailerCoreModule-->RedisCoreModule
  MailerCoreModule-->SequelizeCoreModule
  MailerModule-->ConfigHostModule
  MailerModule-->ConfigModule
  MailerModule-->MailerCoreModule
  MailerModule-->RedisCoreModule
  MailerModule-->SequelizeCoreModule
  MulterModule-->ConfigHostModule
  MulterModule-->ConfigModule
  MulterModule-->MailerCoreModule
  MulterModule-->RedisCoreModule
  MulterModule-->SequelizeCoreModule
  PassportModule-->ConfigHostModule
  PassportModule-->ConfigModule
  PassportModule-->MailerCoreModule
  PassportModule-->RedisCoreModule
  PassportModule-->SequelizeCoreModule
  PodcastModule-->ArticlesModule
  PodcastModule-->ConfigHostModule
  PodcastModule-->ConfigModule
  PodcastModule-->HttpModule
  PodcastModule-->MailerCoreModule
  PodcastModule-->RedisCoreModule
  PodcastModule-->SequelizeCoreModule
  PodcastModule-->UploadModule
  RedisCoreModule-->ConfigHostModule
  RedisCoreModule-->ConfigModule
  RedisCoreModule-->MailerCoreModule
  RedisCoreModule-->SequelizeCoreModule
  RedisModule-->ConfigHostModule
  RedisModule-->ConfigModule
  RedisModule-->MailerCoreModule
  RedisModule-->RedisCoreModule
  RedisModule-->SequelizeCoreModule
  SequelizeCoreModule-->ConfigHostModule
  SequelizeCoreModule-->ConfigModule
  SequelizeCoreModule-->MailerCoreModule
  SequelizeCoreModule-->RedisCoreModule
  SequelizeModule-->ConfigHostModule
  SequelizeModule-->ConfigModule
  SequelizeModule-->MailerCoreModule
  SequelizeModule-->RedisCoreModule
  SequelizeModule-->SequelizeCoreModule
  UploadModule-->ConfigHostModule
  UploadModule-->ConfigModule
  UploadModule-->MailerCoreModule
  UploadModule-->MulterModule
  UploadModule-->RedisCoreModule
  UploadModule-->SequelizeCoreModule
  UsersModule-->ConfigHostModule
  UsersModule-->ConfigModule
  UsersModule-->MailerCoreModule
  UsersModule-->RedisCoreModule
  UsersModule-->SequelizeCoreModule
  UsersModule-->SequelizeModule